import {
  Automerge
} from './_imports'

import {
  DocMutator
} from './doc-mutator'

export function createCommitter(doc: any, action: any, initiator?: any) {
  return new Committer(doc, action, initiator)
}

export class Committer {
  doc: any
  action: any
  name: string
  data: any
  mutator: DocMutator
  initiator: any
  autoGeneratedMessage: string
  autoMessage: boolean = false
  commitHistory: any[]

  constructor(doc: any, action: any, options: any = {}) {
    const {
      initiator,
      autoMessage
    } = options

    this.doc = doc
    this.action = action
    this.name = action.name
    this.data = action.data
    this.mutator = new DocMutator()
    this.initiator = initiator
    this.autoMessage = autoMessage
    this.commitHistory = []
  }

  error(msg: string, data?: any) {
    if (!this.initiator.error) return
    this.initiator.error(msg, data)
  }

  commit(message?: string) {
    message = message || this.autoGenerateMessage()
    if (!message) {
      this.error('Missing or invalid commit message')
    }

    Automerge.change(this.doc, message, this.createCb())
    return this.initiator || this
  }

  createCb() {
    return this[this.name](this.data)
  }

  addNode(data: any) {
    this.autoGeneratedMessage = `added node: ${data.id}`
    return (doc: any) => {
      this.mutator.addNode(doc, data)
    }
  }

  updateNode(data: any) {
    this.autoGeneratedMessage = `updated node: ${data.id}`
    return (doc: any) => {
      this.mutator.updateNode(doc, data)
    }
  }

  replaceNode(data: any) {
    this.autoGeneratedMessage = `replaced node: ${data.id}`
    return (doc: any) => {
      this.mutator.replaceNode(doc, data)
    }
  }

  autoGenerateMessage() {
    return this.autoGeneratedMessage
  }

  removeNode(id: string) {
    this.autoGeneratedMessage = `removed node: ${id}`
    return (doc: any) => {
      this.mutator.removeNode(doc, id)
    }
  }

  edgeLabel(options: any) {
    let {
      id,
      source,
      target,
      directed
    } = options
    const arrow = directed ? '=>' : '<=>'
    return `${id} points ${source} ${arrow} ${target}`
  }

  // such as: from: 'x' to: 'y' or source: 'x' target: 'y'
  addEdge(options: any) {
    options = this.normalizeOpts(options)
    const label = this.edgeLabel(options)
    this.autoGeneratedMessage = `added edge: ${label}`
    return (doc: any) => {
      this.mutator.addEdge(doc, options)
    }
  }

  normalizeOpts(options: any) {
    let {
      id,
      source,
      target,
      from,
      to,
      directed
    } = options
    target = target || to
    source = source || from
    return {
      id,
      source,
      target,
      directed
    }
  }

  updateEdge(options: any) {
    options = this.normalizeOpts(options)
    const label = this.edgeLabel(options)
    this.autoGeneratedMessage = `updated edge: ${label}`
    return (doc: any) => {
      this.mutator.updateEdge(doc, options)
    }
  }

  // such as:
  //   from: 'x' to: 'y'
  //   source: 'x' target: 'y'
  //   id: 'my-edge'
  removeEdge(options: any) {
    options = this.normalizeOpts(options)
    const label = this.edgeLabel(options)
    this.autoGeneratedMessage = `removed edge: ${label}`

    return (doc: any) => {
      this.mutator.removeEdge(doc, options)
    }
  }
}
